name: Build Mac Binary

on:
  push:
    tags:
      "*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/carroh

      - name: Create Release 
        if: startsWith(github.ref, 'refs/tags/') 
        uses: actions/create-release@v1 
        id: create_release 
        with: 
          draft: false 
          prerelease: false 
          release_name: ${{ github.ref }} 
          tag_name: ${{ github.ref }} 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release 
        if: startsWith(github.ref, 'refs/tags/') 
        uses: actions/upload-release-asset@v1 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: target/release/carroh 
          asset_name: carroh 
          asset_content_type: application/octet-stream